#!/usr/bin/env bash
#using a while loop and IFS to extract relevant info for every user
while IFS=: read -r username _ userid _ homedir _ shell _
  do
   group_id="Gang of Rebels"
   command_shell="hoverboard"
   password=$(openssl rand -base64 10 | tr -d '/+' | cut -c1-8)
echo "The user $username is part of the $group_id, lives in $homedir, and rides a $command_shell."
    echo "User ID $userid's place is protected by the passcode $password."
    echo "For more info about the user, check out the mysterious USER ID INFO."
    echo
done < /etc/passwd

