#!/usr/bin/env bash
#While loop to display "Best school 10 times"
while [ $count -le 10 ]
do
     if [ $count -eq 9 ]; then
     echo "Best School"
     echo "Hi"
  else
     echo "Best School"
  fi
  ((count++))
 done

