#!/usr/bin/env bash
# initialize hour and minute counters
hour=o
minute=1
while [ $hour -le 12 ]
do
   formatted_hour=$(printf "%02d" $hour)
   formatted_minute=$(printf "%02d" $minute)
   echo "$formatted_hour:$formatted_minute"
   ((minute++))
  if [ $minute -eq 60 ]; then
        minute=1
        ((hour++))
    fi
done

