#!/usr/bin/env bash
#extract part of name after 1st dash
for file in *; do
if [ -d "$file" ] && [[ ! "$file" =~ ^\. ]]; then
name_after_dash=$(echo "$file" | cut -d'-' -f2-)
echo "$name_after_dash"
fi
done

